using Scriban;

namespace EnumSerializer.Generator;

internal static class SourceGenerationHelper
{
    internal static string GenerateConverterClass(Template template, EnumInfo enumToGenerate)
    {
        var hasUnknownMember = enumToGenerate.Members.Any(
            e => string.Equals(e.Value, "Unknown", StringComparison.OrdinalIgnoreCase)
        );

        var result = template.Render(new
        {
            EnumNamespace = enumToGenerate.Namespace,
            EnumName = enumToGenerate.Name,
            EnumMembers = enumToGenerate.Members,
            HasUnknownMember = hasUnknownMember,
        });

        return result;
    }

    internal const string ConverterTemplate =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the EnumSerializer.Generator source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        using System;
        using System.Runtime.CompilerServices;

        {{~ if enum_namespace ~}}
        namespace {{ enum_namespace }};
        {{~ end ~}}

        internal partial class {{ enum_name }}Converter : global::System.Text.Json.Serialization.JsonConverter<{{ enum_name }}>
        {
            public override void Write(
                global::System.Text.Json.Utf8JsonWriter writer,
                {{ enum_name }} value,
                global::System.Text.Json.JsonSerializerOptions options
            ) =>
                writer.WriteStringValue(value switch
                {
                {{~ for enum_member in enum_members ~}}
                    {{ enum_name }}.{{enum_member.key}} => "{{ enum_member.value }}",
                {{~ end ~}}
                {{~ if has_unknown_member ~}}
                    _ => throw new global::System.Text.Json.JsonException(),
                {{~ else ~}}
                    ({{ enum_name }})0 => "unknown",
                    _ => throw new global::System.Text.Json.JsonException(),
                {{~ end ~}}
                });

            public override {{ enum_name }} Read(
                ref global::System.Text.Json.Utf8JsonReader reader,
                Type typeToConvert,
                global::System.Text.Json.JsonSerializerOptions options
            ) =>
                !global::System.Text.Json.JsonElement.TryParseValue(ref reader, out var element)
                    ? ({{ enum_name }})0
                    : element.Value.ToString() switch
                    {
                    {{~ for enum_member in enum_members ~}}
                        "{{ enum_member.value }}" => {{ enum_name }}.{{ enum_member.key }},
                    {{~ end ~}}
                    {{~ if has_unknown_member ~}}
                        _ => {{ enum_name }}.Unknown,
                    {{~ else ~}}
                        _ => 0,
                    {{~ end ~}}
                    };
        }
        """;
}
