using Scriban;

namespace EnumSerializer.Generator;

internal static class SourceGenerationHelper
{
#if NET8_0_OR_GREATER
    internal const string JsonSerializerOptionsProviderTemplate =
        """
        #if NET8_0_OR_GREATER

        using System.Collections.Generic;

        namespace Telegram.Bot.Converters;

        /// <summary>
        ///
        /// </summary>
        public static partial class JsonSerializerOptionsProvider
        {
            static partial void AddGeneratedConverters(IList<JsonConverter> converters)
            {
                {{~ for enum in enums ~}}
                converters.Add(new global::{{ if enum.namespace }}{{ enum.namespace }}.{{ end }}{{ enum.name }}Converter());
                {{~ end ~}}
            }
        }

        #endif
        """;
#endif

    internal const string ConverterTemplate =
#if NET8_0_OR_GREATER
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the EnumSerializer.Generator source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        {{~ if enum_namespace ~}}
        namespace {{ enum_namespace }};
        {{~ end ~}}

        internal partial class {{ enum_name }}Converter : global::System.Text.Json.Serialization.JsonConverter<global::{{ enum_namespace }}.{{ enum_name }}>
        {
            public override void Write(
                global::System.Text.Json.Utf8JsonWriter writer,
                global::{{ enum_namespace }}.{{ enum_name }} value,
                global::System.Text.Json.JsonSerializerOptions options
            ) =>
                writer.WriteStringValue(value switch
                {
                {{~ for enum_member in enum_members ~}}
                    global::{{ enum_namespace }}.{{ enum_name }}.{{enum_member.key}} => "{{ enum_member.value }}",
                {{~ end ~}}
                {{~ if has_unknown_member ~}}
                    _ => throw new global::System.Text.Json.JsonException(),
                {{~ else ~}}
                    (global::{{ enum_namespace }}.{{ enum_name }})0 => "unknown",
                    _ => throw new global::System.Text.Json.JsonException(),
                {{~ end ~}}
                });

            public override global::{{ enum_namespace }}.{{ enum_name }} Read(
                ref global::System.Text.Json.Utf8JsonReader reader,
                global::System.Type typeToConvert,
                global::System.Text.Json.JsonSerializerOptions options
            ) =>
                !global::System.Text.Json.JsonElement.TryParseValue(ref reader, out var element)
                    ? (global::{{ enum_namespace }}.{{ enum_name }})0
                    : element.Value.ToString() switch
                    {
                    {{~ for enum_member in enum_members ~}}
                        "{{ enum_member.value }}" => global::{{ enum_namespace }}.{{ enum_name }}.{{ enum_member.key }},
                    {{~ end ~}}
                    {{~ if has_unknown_member ~}}
                        _ => global::{{ enum_namespace }}.{{ enum_name }}.Unknown,
                    {{~ else ~}}
                        _ => 0,
                    {{~ end ~}}
                    };
        }
        """;
#else
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the EnumSerializer.Generator source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        {{~ if enum_namespace ~}}
        namespace {{ enum_namespace }};
        {{~ end ~}}

        internal partial class {{ enum_name }}Converter : global::Newtonsoft.Json.JsonConverter<global::{{ enum_namespace }}.{{ enum_name }}>
        {
            public override void WriteJson(JsonWriter writer, global::{{ enum_namespace }}.{{ enum_name }} value, global::Newtonsoft.Json.JsonSerializer serializer) =>
                writer.WriteValue(value switch
                {
                {{~ for enum_member in enum_members ~}}
                    global::{{ enum_namespace }}.{{ enum_name }}.{{enum_member.key}} => "{{ enum_member.value }}",
                {{~ end ~}}
                {{~ if has_unknown_member ~}}
                    _ => throw new global::System.NotSupportedException(),
                {{~ else ~}}
                    (global::{{ enum_namespace }}.{{ enum_name }})0 => "unknown",
                    _ => throw new global::System.NotSupportedException(),
                {{~ end ~}}
                });

            public override global::{{ enum_namespace }}.{{ enum_name }} ReadJson(
                global::Newtonsoft.Json.JsonReader reader,
                global::System.Type objectType,
                global::{{ enum_namespace }}.{{ enum_name }} existingValue,
                bool hasExistingValue,
                global::Newtonsoft.Json.JsonSerializer serializer
            ) =>
                global::Newtonsoft.Json.Linq.Extensions.Value<string>(global::Newtonsoft.Json.Linq.JToken.ReadFrom(reader)) switch
                {
                {{~ for enum_member in enum_members ~}}
                    "{{ enum_member.value }}" => global::{{ enum_namespace }}.{{ enum_name }}.{{ enum_member.key }},
                {{~ end ~}}
                {{~ if has_unknown_member ~}}
                    _ => global::{{ enum_namespace }}.{{ enum_name }}.Unknown,
                {{~ else ~}}
                    _ => 0,
                {{~ end ~}}
                };
        }
        """;
#endif

    internal static string GenerateConverterClass(Template template, EnumInfo enumToGenerate)
    {
        var hasUnknownMember = enumToGenerate.Members.Any(
            e => string.Equals(e.Value, "Unknown", StringComparison.OrdinalIgnoreCase)
        );

        var result = template.Render(new
        {
            EnumNamespace = enumToGenerate.Namespace,
            EnumName = enumToGenerate.Name,
            EnumMembers = enumToGenerate.Members,
            HasUnknownMember = hasUnknownMember,
        });

        return result;
    }

#if NET8_0_OR_GREATER
    internal static string GenerateOptionsProviderClass(Template template, IEnumerable<EnumInfo> enums)
        => template.Render(new { Enums = enums });
#endif
}
